- name: è‡ªåŠ¨æäº¤æ›´æ–°åçš„m3uæ–‡ä»¶
  run: |
    git config --global user.name "GitHub Actions"
    git config --global user.email "actions@github.com"
    git add migufootball.m3u
    git commit -m "ğŸš€ è‡ªåŠ¨æ›´æ–°å’ªå’•è¶³çƒm3uèŠ‚ç›®å•-$(date +%Y%m%d)" || echo "æ— æ›´æ”¹ï¼Œè·³è¿‡æäº¤"
    git push
  env:
    GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
